export const types = {

  FETCH_CHARACTERS_START: '[CHARACTERS] FETCH_CHARACTERS_START',
  FETCH_CHARACTERS_SUCCESS: '[CHARACTERS] FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_ERROR: '[CHARACTERS] FETCH_CHARACTERS_ERROR',

  FETCH_CHARACTER_START: '[CURRENT_CHARACTER] FETCH_CHARACTER_START',
  FETCH_CHARACTER_SUCCESS: '[CURRENT_CHARACTER] FETCH_CHARACTER_SUCCESS',
  FETCH_CHARACTER_ERROR: '[CURRENT_CHARACTER] FETCH_CHARACTER_ERROR',

  FETCH_EPISODES_START: '[EPISODES] FETCH_EPISODES_START',
  FETCH_EPISODES_SUCCESS: '[EPISODES] FETCH_EPISODES_SUCCESS',
  FETCH_EPISODES_ERROR: '[EPISODES] FETCH_EPISODES_ERROR'

}
